### ISSUE TITLE
where to put default.conf

### ISSUE THREAD

**Issue by Zapnologica** [Dynalon/JsonConfig#29]
I am not sure where exactly to put my default.conf file? I have put it in the root directory but when I debug there are 0 keys on my Config.Default instance?

**Comment by Dynalon** [comment]
The `default.conf` is meant to carry sane default values that are provided by the developer - thus you have to embed it as a resource in VS so that it gets loaded (and your users can't edit it). Use a `settings.conf` for your users to overwrite values from the `default.conf`. The `settings.conf` should be in the project root, web root, or next to the executable/assembly.
